name: Reclutamiento de Agente

on: 
    workflow_dispatch:

jobs:
    reporte-de-reclutamiento:
        runs-on: ubuntu-latest

        steps:
            - name: El agente se presenta a la empresa
              run: echo "Soy Lex Luthor, lider de la Legion del Mal"

            - name: Reporte de identidad
              run: |
                echo "Reporte de identidad"
                echo "===================="
                echo ""
                echo "Nombre Clave ${{ github.actor }}"
                echo "Contexto de Github"
                echo "Repo ${{ github.repository }}"
                echo "Operacion: ${{ github.sha }}"
                echo "Metadata: ${{ toJson(github) }}"

            - name: Capacidades del agente
              run: |
                echo "Capacidades del agentedeyecyads: "
                echo "======================"
                echo ""
                echo "Sistema Operativo"
                uname -a
                echo "Habilidades técnicas"
                node --version
                git --version
                python3 --version

            - name: Reconocimiento del terreno
              run: |
                echo "Reconocimiento del terreno"
                ls /