name: Acceso a la fortaleza

on: push

jobs: 
    acceso-a-la-fortaleza-prohibida:
        runs-on: ubuntu-latest

        steps:
            - name: El agente llega a la fortaleza
              run: |
                echo "El agente llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la legión"
                echo ls -la
                echo ""
                echo "✖️ pero que pasó? no hay nada"

            - name: Brainiac desloque ala boveda
              uses: action/checkout@v4
            
            - name: 'Ahora si vamos a ver los planes'
              run: |
                ls -la
                echo "✅ Funciona!"
                echo ""
                echo ""
                echo "Planes: "
                ls planes/
                echo: "Villanos"
                ls villanos/
                echo: "Inteligencia"
                ls inteligencia/