name: Comunicador

on:
    workflow_dispatch:
        inputs:
            villano:
                description: "¿Qué villano envia el mensaje?"
                required: true
                type: choice
                options:
                    - Joker
                    - Thanos
                    - Darth Vader

jobs:
    transmitir-mensaje:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4